### ISSUE TITLE
Why not ChromeHeadless or PhantomJS

### ISSUE THREAD

**Issue by akkuman** [gen2brain/url2img#12]
The phenomenon I can see so far is that every time there are about 500 to 1000 screenshots, the whole program will no longer be able to take screenshots normally.I can only control the program restart by using additional logic.In addition, qTWebKit documentation is relatively few, which is actually a little difficult to maintain for people who are not familiar with it (for example, it took me a lot of time to ignore the pullrequest certificate error last time).

I saw you mention in another issue that Chrome Headless resources are heavy, but PhantomJS is webKit-based and relatively easy to maintain.

**Comment by gen2brain** [comment]
I probably mentioned that WebEngine (included in Qt and based on chrome) is heavy. PhantomJS is deprecated in favor of Chrome Headless I think, but nothing stops you from using it. I don't like the idea to use the whole browser just to take a screenshot. That might work on desktop systems, I don't want that installed on the server.

About your problem, qtwebkit version is still alpha, not even beta.

**Comment by akkuman** [comment]
https://github.com/ariya/phantomjs seems to be being maintained,but not as active
https://hub.docker.com/r/wernight/phantomjs

**Comment by gen2brain** [comment]
Yes, there is this notice "Important: PhantomJS development is suspended until further notice (see #15344 for more details)." and issue https://github.com/ariya/phantomjs/issues/15344.

**Comment by akkuman** [comment]
Thanks
