### ISSUE TITLE
webview useful ?

### ISSUE THREAD

**Issue by ghost** [gen2brain/url2img#3]
thanksfor this - really useful

therecipe/qt now has a webview.

Is this better than using your patch of github.com/therecipe/qt/webkit?

**Comment by gen2brain** [comment]
I will need to check, but it doesn't look like it can be a replacement . I don't see right now how can I create painter from image so it can be rendered. WebView looks like a much simpler qml component, I guess it is useful on mobile platforms where it can use system WebView component.

WebEngine can be a replacement for sure. I used that first, but it cannot be compiled statically, you cannot hide scrollbars, memory usage is higher, sometimes returns white pages etc. And WebKit is worked on again, there was a new release recently.

**Comment by ghost** [comment]
so wait for the new release of webkit ?

btw the webview does not work yet over at therecipe

**Comment by gen2brain** [comment]
There was a new release a month ago https://github.com/annulen/webkit/releases/tag/qtwebkit-tp5 , I will try these days to recompile url2img with new release.

**Comment by joeblew99** [comment]
did you have any luck with this ?

This is really useful.

I am curious what it wil mean if i make an app with this and QT and submit it ot the apple store.
I am guessing that we will need to make i ton IOS, dynamically link to the native webkit on IOS, so apple dont throw it out of the app store.

**Comment by gen2brain** [comment]
New release is uploaded. Did find way to test something with WebView.
