### ISSUE TITLE
some parameters doesn't work

### ISSUE THREAD

**Issue by hbakhtiyor** [gen2brain/url2img#4]
`delay` doesn't work
`height` doesn't work properly, when set to higher, rest of them will become black.

e.g. http://localhost:55888/?url=html5test.com&height=2000&delay=5000

**Comment by gen2brain** [comment]
It works for me when I enter width,  like this /?url=html5test.com&width=2560&height=2000&delay=5000 , delay also works, but maybe maximum of 5000 is not enough. If you use it with Xvfb try to start virtual X with higher resolution.

**Comment by hbakhtiyor** [comment]
i just use your binary with my ubuntu desktop env without any virtual env

**Comment by hbakhtiyor** [comment]
but how to get full screenshot of an entire page?

**Comment by gen2brain** [comment]
I don't think I can get info about page height/content, without some js hack, that is up to you. Just specify large resolution, but with both width and height.

**Comment by hbakhtiyor** [comment]
not sure i understand

**Comment by gen2brain** [comment]
In your example you posted, don't specify just height, also include width of page.

**Comment by gen2brain** [comment]
I don't know how long web page is, so "entire" page is unknown.

**Comment by hbakhtiyor** [comment]
maybe doing with some js tricks?

**Comment by hbakhtiyor** [comment]
also `quality` doesn't work for me

**Comment by hbakhtiyor** [comment]
btw, how to make thumbnail (cropping)?

**Comment by gen2brain** [comment]
New release is uploaded. You can use "full" parameter to capture full page height, e.g. http://imgur.com/a/Ht64k . I will close this one, file new one if you have some issues.

**Comment by hbakhtiyor** [comment]
Awesome
