### ISSUE TITLE
not properly render js heavy apps

### ISSUE THREAD

**Issue by hbakhtiyor** [gen2brain/url2img#5]
maybe to move to newest render engine like qtwebengine 
or use headless chrome with headless_shell 

what do you think?

**Comment by gen2brain** [comment]
I still didn't found time to try with latest qtwebkit preview.  I used qtwebengine at start, but switched to qtwebkit. I had these issues with webengine https://github.com/gen2brain/url2img/issues/3#issuecomment-283351260

**Comment by hbakhtiyor** [comment]
> There was a new release a month ago https://github.com/annulen/webkit/releases/tag/qtwebkit-tp5 , I will try these days to recompile url2img with new release.

do you have any guide how to recompile with the new engine?

>  used qtwebengine at start, but switched to qtwebkit.

any reasons why did you switched?

**Comment by gen2brain** [comment]
I don't have guide, it was difficult for me because I wanted static binary. For shared binary it is much easier but my patch will not work with latest therecipe/qt. I will review everything when i find time, busy with other projects.

Reasons are in comment I posted " it cannot be compiled statically, you cannot hide scrollbars, memory usage is higher, sometimes returns white pages etc." , with webengine you get one huge shared library that eats memory, qtwebkit is more integrated with other Qt components. WebEngine looked like chrome with no connection with Qt.

**Comment by hbakhtiyor** [comment]
I see

**Comment by hugows** [comment]
this is promising and much better than phantomjs :)

**Comment by hugows** [comment]
any idea why i get a black lower half with something like?

http://localhost:55888/?url=estadao.com.br&height=3000&format=png

**Comment by hbakhtiyor** [comment]
> this is promising and much better than phantomjs :)

url2img is not headless

**Comment by gen2brain** [comment]
@hugows try to use Xvfb instead of real X, and start it with resolution that is enough for your width/height.

phantomjs is scriptable, so you can test your app etc, url2img is just a simple solution to grab screenshots. I believe phantomjs also needs X server.

**Comment by hugows** [comment]
yes, thanks - i just want a screengrab
phantomjs rendering is completely broken on the websites i tested!

**Comment by hbakhtiyor** [comment]
@gen2brain phantomjs is truly headless, no need any X dependencies
@hugows yeah, I also tried, phantomjs uses outdated webkit

**Comment by gen2brain** [comment]
I see, phantomjs has custom qpa plugin. https://github.com/ariya/phantomjs/tree/master/src/qt-qpa-platform-plugin . I can try with offscreen plugin and see how that works, that should work without X11.

**Comment by gen2brain** [comment]
New release is uploaded. It uses offscreen platform plugin so it works without X server. New param is added, to capture a page with full page height. Also, binary is recompiled with Qt 5.8 and qtwebkit-tp5 . I will close this one, open a new one if you have issues.
