### ISSUE TITLE
`full` parameters doesn't work properly

### ISSUE THREAD

**Issue by hbakhtiyor** [gen2brain/url2img#6]
tested with apple.com & yahoo.com
`http://localhost:55888/?url=yahoo.com&full=true`

**Comment by gen2brain** [comment]
It should be fixed in 10c8d6fcb5ded623261bd8b1ba5069b34a0d5783 . New binary is uploaded.

**Comment by hbakhtiyor** [comment]
awesome, but taking full shot is a bit wrong size, 

[1366×1851 pixels](https://www.dropbox.com/s/3i3n3qp21gkgtm0/%28JPEG%20Image%2C%201366%C2%A0%C3%97%C2%A01851%20pixels%29.jpeg?dl=0) (wrong size) taken via `url2img`

```
http://localhost:55888/?url=apple.com&full=true&width=1366
```

[1366×1158 pixels](https://www.dropbox.com/s/ohu0sqgcnaefzht/Screenshot-2017-4-24%20Apple.png?dl=0) taken via browser capturing screenshot extension

maybe it takes mobile version

**Comment by gen2brain** [comment]
Depends what they do and how they detect user agent, but current UA qtwebkit returns doesn't look like mobile, you can check on some sites like whatsmyua.info etc.

Perhaps new `ua` parameter should be added.

**Comment by hbakhtiyor** [comment]
maybe to test with the same `ua`

**Comment by gen2brain** [comment]
New version is released and User-Agent parameter is added. I will close this, feel free to open a new issue, if there are issues. Thanks.
