### ISSUE TITLE
performance & memory/cpu usages compare with headless chrome

### ISSUE THREAD

**Issue by hbakhtiyor** [gen2brain/url2img#8]
did you do any measure with headless chrome in terms of performance & memory/cpu usages?

**Comment by gen2brain** [comment]
Nope, the goal of project was to have one binary without dependencies. If I am going to use full browser I can just use some extension then. I tried with WebEngine though, and memory usage was much much higher.

**Comment by hbakhtiyor** [comment]
thanks, but what do you mean by using `some extension`? i think not yet supported extension for headless chrome

**Comment by gen2brain** [comment]
Well, headless or not, it is just parameter you add when starting browser if I am not mistaken. In that case I would just use full (not headless) browser.
